<a href="https://colab.research.google.com/github/victor-68/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy es una libreria de python.
numpy se utiliza para trabajar con
matrices o arreglos
numpy es la abreviatura de "python
numerico"
tambien tiene funciones para trabajar
en el dominio de algebra lineal, la transformada
y las matrices
en python tenemos listas que sirve como matrices, pero son lentas
de procesar. numpy tiene como objetivo proporcionar un objeto de matirzque
que sea 50 veces mas rapido que las listas tradicionales.

In [1]:
#primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


numpy como np general mente se importan bajo el
alias np. en python los alias son un
nombre alternativo para referirse a la
misma cosa


In [2]:
import numpy as np
arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprovando la version de numpy
la cadena de la version se almacena en
el atributo _version_

In [14]:
import numpy as np

print(np.__version__)

2.0.2


numpy creando matrices
crear un objeto ndarray de numpy
numpy se utiliza para trabajar con
matrises. el objeto de matriz se llama
ndarray .podemos crear un numpy
ndarray utilizando la funcion array


In [11]:
import numpy as np
arreglo = np.array(["angel","javier","valerio","victor"])
print(arreglo)
print(type(arreglo))

['angel' 'javier' 'valerio' 'victor']
<class 'numpy.ndarray'>


dimensione en matrices
una demencion en matrices es un nivel
de profundidad de matriz (matirces
anidadas)
una matriz anidada contiene matrices
como elementos
matrices 0-D.son elementos de una
matriz 0-D ejemplos crea una matriz
0-Dcon un valor de 42

In [13]:
import numpy as np
arreglo = np.array (42)
print(arreglo)

42


matirces 1-D
una matriz que tiene matrices 0-D
como unidemenciones 0 1-D.
estas son las matrices mas comunes y
basicas.
ejemplo:crea una matriz de 1-D que
renga los valores 1,2,3,4,5

In [15]:
import numpy as np
arreglo = np.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


matices 2D
una matrices que tiene matrices 1-D
como elementos se denomina matriz 2-D.
a menudo se utiliza para reprecentar
matrices de segundo orden numpy tiene
tiene un submodulo completo dedicado a
operaciones con matrices llamndo numpy.
mat.
ejemplo:crea una matriz

In [16]:
import numpy as np
arreglo = np.array([[1,2,3],[4,5,6]])
print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3-D
una matriz que tiene matrices 2D se
denomina matriz 3D.
estas matrices se utiliza para
reprecentar una matriz de tercer orden.
ejemplo:crea una matriz 3D dos
matirces bidimencionales, ambas
conteniendo dos matrices con los
valores 1,2,3 y 4,5,6.

In [17]:
import numpy as np
arreglo = np.array([[[1,2,3],[4,5,6]]]), [[1,2,3]],[[4,5,6]]
print(arreglo)


(array([[[1, 2, 3],
        [4, 5, 6]]]), [[1, 2, 3]], [[4, 5, 6]])
