<a href="https://colab.research.google.com/github/victor-68/unidad1/blob/main/practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

victor martinez alvarez - practica 7- 25 de septiembre 2025
-------------
slicing numpy
-------------
utiliza step par determinar el paso del corte:

ejemplo: ([1,2,3,4,5,6,7])- devuelve todos los elementos
del indice 1 al indice 5



In [1]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[1:5:2])

[2 4]


ejemplo 2:([1,2,3,4,5,6,7])
devuelve los elementos de la matriz

In [2]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[::2])

[1 3 5 7]


slice de matrices 2D
------------
ejemplo: ([[1,2,3,4,5],[6,7,8,9,10]])
del segundo elemento , corte del indice 1 al
indice 4

---



In [3]:
import numpy as np
arreglo=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[1, 1:4])

[7 8 9]


ejemplo 4: ([[1,2,3,4,5],[6,7,8,9,10]])
de ambos elementos,devuelven el indice 2
--------------------

In [4]:
import numpy as np
arreglo=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 2])

[3 8]


ejemplo 5: ([[1,2,3,4,5],[6,7,8,9,10]])
de ambos elementos corta el indice 1
al indice 4
-----------------

In [5]:
import numpy as np
arreglo=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


ejercicio 1: autonomo del siguiente arrglo,
¿cual es el resultado? ([1,2,3,4,5,6,7,])
corta del 1 elemento al 6 elemento
con paso 2

In [8]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[0:6:2])

[1 3 5]
