<a href="https://colab.research.google.com/github/victor-68/unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

victor martinez alvarez - 24 de septiembre de 2025
practica 6 - corta arreglos numpy
---------------------------------
silice en python significa tomar elementos de
un indice determinado a otro determinado
indice.

pasamos silice en lugar del indice de esta
manera [stard:end]
si no pasamos el inicio se considera 0
si no pasamos el final su longutud
es considerada una matriz de una dimencion
--------------
ejemplo:([1,2,3,4,5,6,7])
por tal los elementos del indice 1 al indice 5
---------

In [1]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[1:5])

[2 3 4 5]


Ejemplo 2:
([1,2,3,4,5,6,7)]
cortar del indice 4 hasta el final de la
matriz
----------------

In [2]:
import numpy as np
arreglo=np.array ([1,2,3,4,5,6,7])
print(arreglo[4:])

[5 6 7]


Ejemplo 3:
([1,2,3,4,5,6,7])
cortar elementos desde el principio hasta el indice 5


In [3]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[:5])

[1 2 3 4 5]


Ejemplo 4:
([1,2,3,4,5,6,7])
corte negativo.utilisamos el operador "menos" para hacer
referencia a un indice desde final.
--------------------------------
cortar desde el indice 1 desde el final

In [4]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[-3:-1])

[5 6]
